Paginate = 6
assetDir = "assets/" 
baseurl = "https://www.investtaxi.info/"
# baseurl = "/"
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
paginatePath = "page"
publishdir = "public"
title = "Invest Taxi"

[Params]
comments = true
commit = false
favicon = "img/favicon.png"
logo = "img/logo2.png" 
rss = true
description= "Invest Taxi"
author = "Lubomur"
url = "https://www.investtaxi.info/"

[[menu.main]]
name = "Про Нас"
url = "#about"
weight = 1
# [[menu.main]]
# name = "Наша Робота"
# url = "/work/"
# weight = 2 
# [[menu.main]]
# name = "Відповідні Авто"
# url = "/auto/"
# weight = 3
[[menu.main]]
name = "Співпраця"
url = "#aption"
weight = 4
# [[menu.main]]
# name = "Алгоритми Співпраці"
# url = "/algorithms/"
# weight = 5
[[menu.main]]
name = "Чому Саме Ми"
url = "#why-we"
weight = 6
[[menu.main]]
name = "Запитання"
url = "#faq"
weight = 7
[[menu.main]]
name = "Контакти"
url = "#contact"
weight = 8



[permalinks]
DefaultContentLanguage = "uk"
metaDataFormat = "md"
post = "/blog/:year/:month/:slug/"
blog = "/blog/:year/:month/:day/:slug"
 
