Paginate = 6
assetDir = "assets/" 
# baseurl = "http://localhost:1313/"
baseurl = "/"
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
paginatePath = "page"
publishdir = "public"
title = "Sea Life Rescue"

[Params]
comments = true
commit = false
favicon = "img/svg/icon.svg"
logo = "img/logo.svg"
logo_mobail = "img/mobail/logo.svg"
rss = true
description= "Sea Life Rescue"
author = "Ken Maff"
url = "https://sealiferescue.netlify.app/"

[[menu.main]]
name = "The Challenge"
url = "/the-challenge/"
weight = 1
[[menu.main]]
name = "Our Solution"
url = "our-solution/"
weight = 2 
[[menu.main]]
name = "Our Technology"
url = "/our-technology/"
weight = 3
[[menu.main]]
name = "Who We Are"
url = "/who-we-are/"
weight = 4
[[menu.main]]
name = "Get Involved"
url = "/get-involved/"
weight = 5



[permalinks]
DefaultContentLanguage = "en"
metaDataFormat = "md"
post = "/blog/:year/:month/:slug/"
blog = "/blog/:year/:month/:day/:slug"
 
